spring:
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      maximum-pool-size: 3
      idle-timeout: 30000
      pool-name: SpringBootHikariCP
      driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    name: trainlab
  flyway:
      enabled: true
      baseline-on-migrate: true
      baseline-description: Flyway Scripts
      locations: classpath:/db.migration
      user: ${spring.datasource.username}
      password: ${spring.datasource.password}
      url: ${spring.datasource.url}
      default-schema: public
      validate-on-migrate: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  servlet:
    encoding:
      charset: utf-8