version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: doadmin
      POSTGRES_PASSWORD: AVNS_U3ZPhA1L6ysAq507vy-
      POSTGRES_DB: postgres
    ports:
      - "5432:25060"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: