version: '1.0'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: trainlab
      POSTGRES_PASSWORD: trainlab
      POSTGRES_DB: trainlab
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/trainlab
      SPRING_DATASOURCE_USERNAME: trainlab
      SPRING_DATASOURCE_PASSWORD: trainlab