version: '3'

services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: