version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:25060"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    command: migrate
    environment:
      - FLYWAY_URL=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - FLYWAY_USER=${DB_USERNAME}
      - FLYWAY_PASSWORD=${DB_PASSWORD}
      - FLYWAY_LOCATIONS=/common/src/main/resources/db/migration

  api:
    build:
      context: ../../../..
      dockerfile: Dockerfile
    ports:
      - "8888:8080"
    depends_on:
      - postgres

volumes:
  postgres_data: