CREATE TABLE refresh_sessions (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    refresh_token UUID NOT NULL,
    fingerprint VARCHAR(200) NOT NULL, /*unique hash which generated by the client based on some browser parameters (user-agent, ip, etc)*/
    expired_at TIMESTAMP(6) NOT NULL,
    issued_at TIMESTAMP(6) NOT NULL DEFAULT now()
);