CREATE TABLE IF NOT EXISTS public.test (
                             id SERIAL PRIMARY KEY,
                             title VARCHAR(255) NOT NULL,
                             description TEXT,
                             specialty VARCHAR(20)
);
CREATE  TABLE  IF NOT EXISTS  public.question (
                                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                  question_txt VARCHAR(255),
                                                  question_num INT
);

CREATE TABLE IF NOT EXISTS  public.answer (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               answer_txt VARCHAR(255),
                               answer_num INT,
                               is_correct BOOLEAN,
                               question_id BIGINT,
                               CONSTRAINT fk_question_id FOREIGN KEY (question_id) REFERENCES public.question(id)
);



CREATE TABLE IF NOT EXISTS public.test_questions (
                                       test_id INT REFERENCES public.test(id),
                                       question_id INT REFERENCES public.question(id),
                                       PRIMARY KEY (test_id, question_id)
);


